import { verifySignature } from 'src/utils';
import { BaseSignatureMetadata } from 'src/type';

/**
 * Verify the signature generated by the generate method.
 * @param {BaseSignatureMetadata} metadata output of the generate method to get verified
 * @returns {boolean} result
 */
const verifyServerMetadataSignature = (
  metadata: BaseSignatureMetadata,
): boolean => {
  return verifySignature(metadata, {
    signature: (metadata.reference.pop().body as BaseSignatureMetadata).signature,
  });
};

export default verifyServerMetadataSignature;
