import { verifyDigest } from 'src/utils';
import { AuthorDigestMetadata, PostMetadata } from '@/src/type';

/**
 * Verify the digest generated by the generate method.
 * @param {AuthorDigestMetadata} metadata output of the generate method to get verified
 * @returns {boolean} result
 */
const verify = (metadata: AuthorDigestMetadata): boolean => {
  const { digest } = metadata;
  const postMetadata: PostMetadata = {
    title: metadata.title,
    categories: metadata.categories,
    content: metadata.content,
    cover: metadata.cover,
    license: metadata.license,
    summary: metadata.summary,
    tags: metadata.tags,
  };

  const timestamp = metadata.ts;
  return verifyDigest(digest, postMetadata, timestamp);
};

export default verify;
