import { verifySignature } from 'src/utils';
import { SignatureMetadata } from '@/src/type';

/**
 * Verify the signature generated by the generate method.
 * @param {SignatureMetadata} metadata output of the generate method to get verified
 * @returns {boolean} result
 */
const verifyServerMetadataSignature = (
  metadata: SignatureMetadata,
): boolean => {
  return verifySignature(metadata, {
    signature: (metadata.reference.pop().body as SignatureMetadata).signature,
  });
};

export default verifyServerMetadataSignature;
