// generated by curve25519-js
export type KeyPair = {
  public: Uint8Array;
  private: Uint8Array;
};
export type KeyValuePair = [string, string];

export type MetadataInPayload = {
  hash: string;
  nonce: string;
  claim: string;
};

export type PostMetadata = {
  title: string;
  categories: string;
  content: string;
  cover: string;
  licence: string;
  summary: string;
  tags: string;
};

export type AuthorDigestRequestMetadata = {
  '@context': 'https://metanetwork.online/ns/cms';
  type: 'author-digest';
  algorithm: 'sha256' | 'sha512';
  version: string;
  title: string;
  categories: string;
  content: string;
  cover: string;
  licence: string;
  summary: string;
  tags: string;
  digest: string;
  nonce: string;
  claim: string;
  ts: number;
};

export type SignatureMetadata = {
  '@context': 'https://metanetwork.online/ns/cms';
  type: string;
  signatureAlgorithm: 'curve25519';
  version: string;
  publicKey: string;
  signature: string;
  nonce: string;
  claim: string;
  ts: number;
  reference: {
    refer: string;
    body: SignatureMetadata | AuthorDigestRequestMetadata;
  }[];
};

export type AuthorSignatureMetadata = SignatureMetadata & { digest: string };
