import {
  createNonce,
  createSignature,
  createKeyValueByMetadataPayload,
} from 'src/utils';
import {
  KeyPair,
  AuthorPostSignatureMetadata,
  MetadataInPayloadWithDigest,
} from 'src/type';

/**
 * Generate signature metadata for the author's post digest.
 * @param {KeyPair} authorKeys The author's keys to use for signing.
 * @param {string} serverDomain The author claims to publish their post to this domain.
 * @param {string} digest Should be generated by author-digest module.
 * @returns {AuthorPostSignatureMetadata} The author's signature metadata of the post digest.
 */
const generateAuthorPostSignMetadata = (
  authorKeys: KeyPair,
  serverDomain: string,
  digest: string,
): AuthorPostSignatureMetadata => {
  const publicKey = authorKeys.public;

  const authorPostSignatureMetadataHeader: Partial<AuthorPostSignatureMetadata> =
    {
      '@context': 'https://metanetwork.online/ns/cms',
      '@type': 'author-digest-sign',
      '@version': '2.0.0',
      signatureAlgorithm: 'curve25519',
      publicKey,
    };

  const authorPostSignaturePayload: Partial<MetadataInPayloadWithDigest> = {
    digest,
    nonce: createNonce(),
    claim: `I signed with my key ${publicKey} from this device: I authorize ${serverDomain} to publish this post and upload its metadata for notarization.`,
  };

  const { payload, timestamp } = createKeyValueByMetadataPayload(
    authorPostSignaturePayload,
  );
  const signature = createSignature(authorKeys.private, payload);

  const authorPostSignatureMetadata = {
    ...authorPostSignatureMetadataHeader,
    ...authorPostSignaturePayload,
    signature,
    ts: timestamp,
  };
  return authorPostSignatureMetadata as AuthorPostSignatureMetadata;
};

export default generateAuthorPostSignMetadata;
