import { verifySignature } from 'src/utils';
import { SignatureMetadata } from '@/type';

/**
 * Verify the signature generated by the generate method.
 * @param {SignatureMetadata} metadata output of the generate method to get verified
 * @returns {boolean} result
 */
const verifyAuthorPublishMetaSpaceRequestMetadataSignature = (
  metadata: SignatureMetadata,
): boolean => {
  return verifySignature(metadata);
};

export default verifyAuthorPublishMetaSpaceRequestMetadataSignature;
