// generated by curve25519-js
export type KeyPair = {
  public: string;
  private: string;
};
export type KeyValuePair = [string, string];

export type MetadataInPayload = {
  nonce: string;
  claim: string;
};

export type MetadataInPayloadWithDigest = MetadataInPayload & {
  digest: string;
};

export type MetadataInPayloadWithSignature = MetadataInPayload & {
  signature: string;
};

export type BaseSignatureMetadata = {
  '@context': 'https://metanetwork.online/ns/cms';
  '@type': string;
  '@version': string;
  signatureAlgorithm: 'curve25519';
  publicKey: string;
  signature: string;
  nonce: string;
  claim: string;
  ts: number;
  reference: {
    refer: string;
    rel: string;
    body: any;
  }[];
};
