// generated by curve25519-js
export type KeyPair = {
  public: string;
  private: string;
};
export type KeyValuePair = [string, string];

export type MetadataInPayload = {
  nonce: string;
  claim: string;
};

export type MetadataInPayloadWithDigest = MetadataInPayload & {
  digest: string;
};

export type MetadataInPayloadWithSignature = MetadataInPayload & {
  signature: string;
};

export type PostMetadata = {
  title: string;
  categories: string;
  content: string;
  cover: string;
  license: string;
  summary: string;
  tags: string;
};

export type AuthorDigestMetadata = {
  '@context': 'https://metanetwork.online/ns/cms';
  '@type': 'author-digest';
  '@version': string;
  algorithm: 'sha256' | 'sha512';
  title: string;
  categories: string;
  content: string;
  cover: string;
  license: string;
  summary: string;
  tags: string;
  digest: string;
  nonce: string;
  claim: string;
  ts: number;
};

export type SignatureMetadata = {
  '@context': 'https://metanetwork.online/ns/cms';
  '@type': string;
  '@version': string;
  signatureAlgorithm: 'curve25519';
  publicKey: string;
  signature: string;
  nonce: string;
  claim: string;
  ts: number;
  reference: {
    refer: string;
    rel: string;
    body: SignatureMetadata | AuthorDigestMetadata;
  }[];
};

export type AuthorSignatureMetadata = SignatureMetadata & { digest: string };
