import { verifySignature } from 'src/utils';
import { MediaMetadataInPayload, AuthorMediaSignatureMetadata } from 'src/type';

/**
 * Verify the signature generated by the generate method.
 * @param {AuthorMediaSignatureMetadata} metadata output of the generate method to get verified
 * @returns {boolean} result
 */
const verifyAuthorMediaMetadataSignature = (
  metadata: AuthorMediaSignatureMetadata,
): boolean => {
  const payload: Partial<MediaMetadataInPayload> = {
    platformHash: metadata.platformHash,
    platform: metadata.platform,
    contentType: metadata.contentType,
  };

  return verifySignature(metadata, payload);
};

export default verifyAuthorMediaMetadataSignature;
