import { verifySignature } from 'src/utils';
import { AuthorMediaSignatureMetadata } from '@/src/type';

/**
 * Verify the signature generated by the generate method.
 * @param {AuthorMediaSignatureMetadata} metadata output of the generate method to get verified
 * @returns {boolean} result
 */
const verifyAuthorMediaMetadataSignature = (
  metadata: AuthorMediaSignatureMetadata,
): boolean => {
  return verifySignature(metadata, { hash: metadata.hash });
};

export default verifyAuthorMediaMetadataSignature;
