import { verifySignature } from 'src/utils';
import { AuthorSignatureMetadata } from '@/src/type';

/**
 * Verify the signature generated by the generate method.
 * @param {AuthorSignatureMetadata} metadata output of the generate method to get verified
 * @returns {boolean} result
 */
const verifyAuthorDigestMetadataSignature = (
  metadata: AuthorSignatureMetadata,
): boolean => {
  return verifySignature(metadata, { digest: metadata.digest });
};

export default verifyAuthorDigestMetadataSignature;
