import { verifySignature } from 'src/utils';
import { AuthorPostSignatureMetadata } from 'src/type';

/**
 * Verify the signature generated by the generate method.
 * @param {AuthorPostSignatureMetadata} metadata output of the generate method to get verified
 * @returns {boolean} result
 */
const verifyAuthorDigestMetadataSignature = (
  metadata: AuthorPostSignatureMetadata,
): boolean => {
  return verifySignature(metadata, { digest: metadata.digest });
};

export default verifyAuthorDigestMetadataSignature;
